# frozen_string_literal: true

source 'https://rubygems.org'

gem 'sidekiq', '~> 8.1'
gem 'ransack', '~> 4.4'
gem 'rails', '~> 8.1'
gem 'pundit', '~> 2.5'
gem 'puma', '~> 8.0'
gem 'pg', '~> 1.6'
gem 'redis', '~> 5.0'
